language: c
compiler:
  - gcc
cache:
  directories:
    - $HOME/OpenBlasInstall
    - $HOME/torch
sudo: false
env:
  - TORCH_LUA_VERSION=LUAJIT21
  - TORCH_LUA_VERSION=LUA52
addons:
  apt:
    packages:
      - cmake
      - gfortran
      - gcc-multilib
      - gfortran-multilib
      - liblapack-dev
      - build-essential
      - gcc
      - g++
      - curl
      - libreadline-dev
      - git-core
      - libqt4-core
      - libqt4-gui
      - libqt4-dev
      - libjpeg-dev
      - libpng-dev
      - ncurses-dev
      - imagemagick
      - libzmq3-dev
      - gfortran
      - unzip
      - gnuplot
      - gnuplot-x11
install:
  - export ROOT_TRAVIS_DIR=$(pwd)
  - export INSTALL_PREFIX=~/torch/install
  - export PATH=${INSTALL_PREFIX}/bin:$PATH
  - ls $HOME/OpenBlasInstall/lib ||
    (cd /tmp/
    && git clone https://github.com/xianyi/OpenBLAS.git -b master
    && cd OpenBLAS
    && (make NO_AFFINITY=1 -j$(getconf _NPROCESSORS_ONLN) 2>/dev/null >/dev/null)
    && make PREFIX=$HOME/OpenBlasInstall install)
  - ls $INSTALL_PREFIX ||
    (git clone https://github.com/torch/distro.git ~/torch --recursive
    && cd ~/torch
    && git submodule update --init --recursive
    && mkdir build && cd build
    && export CMAKE_LIBRARY_PATH=$HOME/OpenBlasInstall/include:$HOME/OpenBlasInstall/lib:$CMAKE_LIBRARY_PATH
    && cmake .. -DCMAKE_INSTALL_PREFIX="${INSTALL_PREFIX}" -DCMAKE_BUILD_TYPE=Release -DWITH_${TORCH_LUA_VERSION}=ON
    && make && make install
    && cd $ROOT_TRAVIS_DIR
    && export LD_LIBRARY_PATH=${INSTALL_PREFIX}/lib:$LD_LIBRARY_PATH
    && luarocks install torch
    && luarocks install nn
    && luarocks install nngraph
    && luarocks install tds
    && luarocks install bit32 || true
    && luarocks install luacheck
    && luarocks install penlight
    && luarocks install optim
    && luarocks install luacov)
before_script:
  - export LUA=$(which luajit lua | head -n 1)
script:
  - luacheck *lua onmt/ tools/ benchmark/ test/
  - luarocks make rocks/opennmt-scm-1.rockspec
  - sh test/tokenization/test.sh
  - ${LUA} -lluacov test/test.lua -e ${LUA}
  - luacov
after_success:
  - bash <(curl -s https://codecov.io/bash)
